app = "myapp"

# This may be removed in order to fallback to Nginx
# e.g. for fine-grained control over the cache headers
[[statics]]
  guest_path = "/usr/share/nginx/html"
  url_prefix = "/"

# Minimal config for exposing Nginx
[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
